name: FoxTreme Hagos Builder

on:
  workflow_dispatch:
    inputs:
      SYNC_URL:
        description: 'OrangeFox Manifest Sync URL'
        required: true
        default: 'https://gitlab.com/OrangeFox/sync.git'
      MANIFEST_BRANCH:
        description: 'OrangeFox Branch'
        required: true
        default: '12.1'
      DEVICE_TREE_URL:
        description: 'Device Tree URL'
        required: true
        default: 'https://github.com/ExtremeXT/android_device_samsung_beyond2lte'
      DEVICE_TREE_BRANCH:
        description: 'Device Tree Branch'
        required: true
        default: 'android-14'
      DEVICE_PATH:
        description: 'Local Device Path'
        required: true
        default: 'device/samsung/beyond2lte'
      DEVICE_NAME:
        description: 'Device Codename'
        required: true
        default: 'beyond2lte'
      MAKEFILE_NAME:
        description: 'Makefile Name'
        required: true
        default: 'twrp_beyond2lte'
      BUILD_TARGET:
        description: 'Build Target (recovery/boot)'
        required: true
        default: 'recovery'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create workspace
      run: |
        mkdir -p workspace && cd workspace
        echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT
      id: ws

    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install -y \
          git wget curl unzip python3 bc bison build-essential \
          zip flex libncurses5-dev libssl-dev ccache \
          openjdk-11-jdk lzop aria2 rsync

    - name: Install Android SDK
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-9123335_latest.zip -O sdk.zip
        unzip sdk.zip -d android-sdk
        mkdir -p $HOME/android-sdk/cmdline-tools
        mv android-sdk/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=${HOME}/android-sdk \
          "platform-tools" "platforms;android-29"

    - name: Export environment vars
      run: |
        echo "export PATH=$HOME/android-sdk/platform-tools:$HOME/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
        echo "export ALLOW_MISSING_DEPENDENCIES=true" >> $GITHUB_ENV
        echo "export OF_PATCH_AVB20=true" >> $GITHUB_ENV
        echo "export OF_NO_MIUI_PATCH_WARNING=true" >> $GITHUB_ENV
        echo "export FOX_USE_BASH_SHELL=true" >> $GITHUB_ENV
        echo "export FOX_ADVANCED_SECURITY=true" >> $GITHUB_ENV

    - name: Install repo tool
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo "export PATH=~/bin:$PATH" >> $GITHUB_ENV

    - name: Sync OrangeFox sources
      run: |
        cd ${{ steps.ws.outputs.workspace-folder }}
        git clone ${{ github.event.inputs.SYNC_URL }} sync
        cd sync
        ./orangefox_sync.sh --branch ${{ github.event.inputs.MANIFEST_BRANCH }} \
          --path ../fox_${{ github.event.inputs.MANIFEST_BRANCH }}

    - name: Clone device tree
      run: |
        cd ${{ steps.ws.outputs.workspace-folder }}/fox_${{ github.event.inputs.MANIFEST_BRANCH }}
        git clone ${{ github.event.inputs.DEVICE_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ${{ github.event.inputs.DEVICE_PATH }}

    - name: Set swap (12GB)
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Build recovery image
      run: |
        cd ${{ steps.ws.outputs.workspace-folder }}/fox_${{ github.event.inputs.MANIFEST_BRANCH }}
        source build/envsetup.sh
        lunch ${{ github.event.inputs.MAKEFILE_NAME }}-eng
        mka ${{ github.event.inputs.BUILD_TARGET }}image -j$(nproc --all)

    - name: List output files
      run: |
        ls -lh ${{ steps.ws.outputs.workspace-folder }}/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}

    - name: Upload recovery to GitHub Releases
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ${{ steps.ws.outputs.workspace-folder }}/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/*.img
        tag_name: FoxTreme-${{ github.run_id }}
        name: FoxTreme Build - ${{ github.run_id }}
        body: |
          Device: ${{ github.event.inputs.DEVICE_NAME }}
          Branch: ${{ github.event.inputs.MANIFEST_BRANCH }}
          Target: ${{ github.event.inputs.BUILD_TARGET }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
